import { title } from "process";

export const cookieContent = {
  keyTerms: {
    title: "Definitions and key terms",
    description:
      "To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:",
    lists: [
      {
        topic: "Cookie:",
        description:
          "small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.",
      },
      {
        topic: "Company:",
        description:
          "when this policy mentions “Company”, “we”, “us”, or “our” it refers to shpper, that is responsible for your information under this Cookie Policy.",
      },
      {
        topic: "Device:",
        description:
          "any internet connected device such as a phone, tablet, computer or any other device that can be used to visit shpper and use the services.",
      },
      {
        topic: "Personal Data:",
        description:
          "any information that directly, indirectly, or in connection with other information “including a personal identification numbe” allows for the identification or identifiability of a natural person.",
      },
      {
        topic: "Service:",
        description:
          "refers to the service provided by shpper as described in the relative terms (if available) and on this platform.",
      },
      {
        topic: "Third-party service:",
        description:
          " refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",
      },
      {
        topic: "You:",
        description:
          "a person or entity that is registered with shpper to use the Services.",
      },
    ],
  },

  Introduction: {
    title: "Introduction",
    terms: [
      "This Cookie Policy explains how shpper and its affiliates (collectively “shpper”, “we”, “us”, and “ours”), use cookies and similar technologies to recognize you when you visit our website/app, including without limitation shpper.net and any related URLs, mobile or localized versions and related domains / sub-domains (“Websites”). It explains what these technologies are and why we use them, as well as the choices for how to control them.",
    ],
  },
  cookie: {
    title: "What is a cookie?",
    terms: [
      "A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They’re completely safe and can’t be used to run programs or deliver viruses to your device.",
    ],
  },
  cookieUse: {
    title: "Why do we use cookies?",
    description: [
      "We use first party and/or third party cookies on our website/app for various purposes such as:",
    ],
    lists: [
      {
        description:
          "To facilitate the operation and functionality of our website/app",
      },
      {
        description:
          "To improve your experience of our website/app and make navigating around them quicker and easier",
      },
      {
        description:
          "To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you",
      },
      {
        description:
          "To analyze how our website/app is used and how best we can customize it",
      },
      {
        description:
          "To identify future prospects and personalize marketing and sales interactions with it",
      },
      {
        description:
          "To facilitate the tailoring of online advertising to your interests",
      },
    ],
  },
  cookieType: {
    title: "What type of cookies does shpper use?",
    terms: [
      "Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called “first party cookies”.",
      "Strictly Necessary cookies are necessary for our website/app to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website/app and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website/app.",
      "We use the following types of cookies in our website/app:",
    ],
  },
  cookieEssential: {
    title: "Essential Cookies",
    terms: [
      "We use essential cookies to make our website/app work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn’t be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.",
    ],
  },
  cookiePerformace: {
    title: "Performance and Functionality Cookies",
    terms: [
      "These cookies are used to enhance the performance and functionality of our website/app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website/app as we would not be able to remember that you had logged in previously.",
    ],
  },
  cookieMarketing: {
    title: "Marketing Cookies",
    terms: [
      "These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.",
    ],
  },
  cookieAnalytics: {
    title: "Analytics and Customization Cookies",
    terms: [
      "These cookies collect information that is used to help us understand how our website/app is being used or how effective our marketing campaigns are, or to help us customize our website/app for you.",
      "We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website/app. Further information on how Google collects and uses this data can be found at: ",
      "https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics on our Websites by visiting: https://tools.google.com/dlpage/gaoptout.",
    ],
  },
  cookieAdvertising: {
    title: "Advertising Cookies",
    terms: [
      "These cookies collect information over time about your online activity on the website/app and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it’s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.",
    ],
  },
  cookieSocial: {
    title: "Social Media Cookies",
    terms: [
      "These cookies are used when you share information using a social media sharing button or ‘like’ button on our Site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.",
    ],
  },
  cookieThirdParty: {
    title: "Third Party Cookies",
    terms: [
      "Some cookies that have been set on our website/app are not set on a first party basis by shpper. The Websites can be embedded with content from third parties to serve advertising. These third-party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third-party cookies as cookies can only be accessed by the third party that originally set them.",
    ],
  },
  cookieManage: {
    title: "How you can manage cookies?",
    description: [
      "Most browsers allow you to control cookies through their ‘settings’ preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.",
      "Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.",
    ],
    lists: [
      {
        description: "Google Chrome",
      },
      {
        description: "Internet Explorer",
      },
      {
        description: "Mozilla Firefox",
      },
      {
        description: "Safari (Desktop)",
      },
      {
        description: "Safari (Mobile)",
      },
      {
        description: "Android Browser",
      },
      {
        description: "Opera",
      },
      {
        description: "Opera Mobile",
      },
    ],
  },
  cookieBlocking: {
    title: "Blocking and disabling cookies and similar technologies",
    terms: [
      "Wherever you’re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website/app from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g., saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser’s help menu for more information.",
    ],
  },
  cookieChanges: {
    title: "Blocking and disabling cookies and similar technologies",
    terms: [
      "Wherever you’re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website/app from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g., saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser’s help menu for more information.",
    ],
  },
  Consent: {
    title: "Your Consent",
    terms: [
      "By using our website/app, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.",
    ],
  },
};
